2019-05-15 09:34:54,034-F:/work/webservice_practice/common/my_log.py-[DEBUG]-[my_log.py:33]-[日志信息]:这是测试数据！
2019-05-15 10:36:54,193-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 10:36:54,224-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常操作
2019-05-15 10:36:56,881-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：ip为空
2019-05-15 10:36:57,088-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：短信模板为空
2019-05-15 10:36:57,232-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：手机号为空
2019-05-15 10:36:57,384-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：短信模板非1
2019-05-15 10:36:57,619-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：错误的手机号码
2019-05-15 10:36:58,136-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 10:41:37,044-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 10:41:37,080-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常操作
2019-05-15 10:44:09,084-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 10:44:09,094-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常操作
2019-05-15 10:44:10,316-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：ip为空
2019-05-15 10:44:13,478-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：短信模板为空
2019-05-15 10:44:13,603-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：手机号为空
2019-05-15 10:44:13,778-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：短信模板非1
2019-05-15 10:44:13,943-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：错误的手机号码
2019-05-15 10:44:17,159-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 10:47:03,035-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 10:47:03,053-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常操作
2019-05-15 10:47:04,054-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：ip为空
2019-05-15 10:47:04,257-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：短信模板为空
2019-05-15 10:47:04,493-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：手机号为空
2019-05-15 10:47:04,632-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：短信模板非1
2019-05-15 10:47:04,819-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：错误的手机号码
2019-05-15 10:47:05,025-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 10:59:42,610-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 10:59:42,626-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常操作
2019-05-15 10:59:43,160-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：ip为空
2019-05-15 10:59:43,415-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：短信模板为空
2019-05-15 10:59:43,661-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：手机号为空
2019-05-15 10:59:43,935-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：短信模板非1
2019-05-15 10:59:44,243-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：错误的手机号码
2019-05-15 10:59:44,517-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 11:05:48,929-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 11:05:48,936-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常操作
2019-05-15 11:05:49,575-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：ip为空
2019-05-15 11:05:51,040-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：短信模板为空
2019-05-15 11:05:51,442-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：手机号为空
2019-05-15 11:05:52,087-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：短信模板非1
2019-05-15 11:05:55,366-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：错误的手机号码
2019-05-15 11:05:55,652-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 11:07:56,283-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 11:07:56,293-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常操作
2019-05-15 11:07:57,033-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：ip为空
2019-05-15 11:07:57,399-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：短信模板为空
2019-05-15 11:07:57,675-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：手机号为空
2019-05-15 11:07:57,996-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：短信模板非1
2019-05-15 11:07:58,340-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：错误的手机号码
2019-05-15 11:07:58,644-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 11:09:08,954-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 11:09:08,959-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常操作
2019-05-15 11:09:09,478-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：ip为空
2019-05-15 11:09:09,735-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：短信模板为空
2019-05-15 11:09:10,027-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：手机号为空
2019-05-15 11:09:10,289-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：短信模板非1
2019-05-15 11:09:10,572-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：错误的手机号码
2019-05-15 11:09:10,829-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 11:19:57,794-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 11:19:57,798-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常操作
2019-05-15 11:19:58,427-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：ip为空
2019-05-15 11:19:58,772-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：短信模板为空
2019-05-15 11:19:59,970-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：手机号为空
2019-05-15 11:20:00,316-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：短信模板非1
2019-05-15 11:20:00,739-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：错误的手机号码
2019-05-15 11:20:01,077-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 13:43:53,489-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 13:43:53,491-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常操作
2019-05-15 13:43:58,449-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：ip为空
2019-05-15 13:43:58,530-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：短信模板为空
2019-05-15 13:43:58,629-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：手机号为空
2019-05-15 13:43:58,763-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：短信模板非1
2019-05-15 13:43:58,855-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：错误的手机号码
2019-05-15 13:43:58,929-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 13:48:03,067-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 13:48:03,069-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常操作
2019-05-15 13:48:03,803-F:\work\webservice_practice\testcase\test_sendMCode.py-[ERROR]-[my_log.py:39]-[日志信息]:断言出错,信息是： :: ok != 手机号码错误
2019-05-15 13:48:03,859-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：ip为空
2019-05-15 13:48:04,237-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：短信模板为空
2019-05-15 13:48:05,104-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：手机号为空
2019-05-15 13:48:05,433-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：短信模板非1
2019-05-15 13:48:05,726-F:\work\webservice_practice\testcase\test_sendMCode.py-[ERROR]-[my_log.py:39]-[日志信息]:断言出错,信息是： :: 短信模板配置错误 != 手机号码错误
2019-05-15 13:48:05,733-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：错误的手机号码
2019-05-15 13:48:06,060-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 13:49:13,061-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 13:49:13,065-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常操作
2019-05-15 13:49:14,634-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：ip为空
2019-05-15 13:49:14,946-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：短信模板为空
2019-05-15 13:49:15,351-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：手机号为空
2019-05-15 13:49:15,806-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：短信模板非1
2019-05-15 13:49:16,143-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：错误的手机号码
2019-05-15 13:49:17,272-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 14:29:36,501-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 14:29:36,548-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常操作
2019-05-15 14:29:37,490-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：ip为空
2019-05-15 14:29:38,125-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：短信模板为空
2019-05-15 14:29:38,522-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：手机号为空
2019-05-15 14:29:39,549-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：短信模板非1
2019-05-15 14:29:40,630-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：错误的手机号码
2019-05-15 14:29:41,006-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 14:43:39,345-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 14:43:39,554-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常操作
2019-05-15 14:43:40,767-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：ip为空
2019-05-15 14:43:40,812-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：短信模板为空
2019-05-15 14:43:40,930-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：手机号为空
2019-05-15 14:43:41,143-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：短信模板非1
2019-05-15 14:43:41,286-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：错误的手机号码
2019-05-15 14:43:41,441-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 14:46:13,763-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 14:46:14,044-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常操作
2019-05-15 14:46:16,487-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：ip为空
2019-05-15 14:46:16,776-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：短信模板为空
2019-05-15 14:46:17,104-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：手机号为空
2019-05-15 14:46:17,387-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：短信模板非1
2019-05-15 14:46:17,726-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：错误的手机号码
2019-05-15 14:46:18,059-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 16:40:14,768-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:------开始执行测试用例-----
2019-05-15 16:40:14,936-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 16:40:14,952-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 16:40:14,954-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：同一个用户名进行注册
2019-05-15 16:40:14,957-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：验证码和手机号不匹配
2019-05-15 16:40:14,960-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：验证码失效
2019-05-15 16:40:14,968-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：验证码为空
2019-05-15 16:40:14,975-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：验证码少于6位
2019-05-15 16:40:14,980-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：验证码多于6位
2019-05-15 16:40:15,010-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：验证码包含其他字符
2019-05-15 16:40:15,020-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：用户名为空
2019-05-15 16:40:15,024-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第11条测试用例：渠道信息非1、2、3
2019-05-15 16:40:15,030-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第12条测试用例：渠道信息非数字
2019-05-15 16:40:15,036-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第13条测试用例：渠道信息为空
2019-05-15 16:40:15,040-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第14条测试用例：密码为空
2019-05-15 16:40:15,043-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第15条测试用例：手机号少于11位
2019-05-15 16:40:15,052-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第16条测试用例：手机号多余11位
2019-05-15 16:40:15,055-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第17条测试用例：手机号包含非数字
2019-05-15 16:40:15,062-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第18条测试用例：手机号为空
2019-05-15 16:40:15,073-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第19条测试用例：错误的IP地址格式_1
2019-05-15 16:40:15,075-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第20条测试用例：错误的IP地址格式_2
2019-05-15 16:40:15,084-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第21条测试用例：IP地址为空
2019-05-15 16:40:15,087-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 16:40:38,258-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:------开始执行测试用例-----
2019-05-15 16:40:38,402-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 16:40:38,631-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 16:40:38,674-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：同一个用户名进行注册
2019-05-15 16:40:38,679-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：验证码和手机号不匹配
2019-05-15 16:40:38,691-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：验证码失效
2019-05-15 16:40:38,704-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：验证码为空
2019-05-15 16:40:38,711-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：验证码少于6位
2019-05-15 16:40:38,720-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：验证码多于6位
2019-05-15 16:40:38,730-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：验证码包含其他字符
2019-05-15 16:40:38,752-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：用户名为空
2019-05-15 16:40:38,758-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第11条测试用例：渠道信息非1、2、3
2019-05-15 16:40:38,791-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第12条测试用例：渠道信息非数字
2019-05-15 16:40:38,803-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第13条测试用例：渠道信息为空
2019-05-15 16:40:38,822-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第14条测试用例：密码为空
2019-05-15 16:40:38,845-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第15条测试用例：手机号少于11位
2019-05-15 16:40:38,856-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第16条测试用例：手机号多余11位
2019-05-15 16:40:38,875-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第17条测试用例：手机号包含非数字
2019-05-15 16:40:38,896-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第18条测试用例：手机号为空
2019-05-15 16:40:38,906-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第19条测试用例：错误的IP地址格式_1
2019-05-15 16:40:38,916-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第20条测试用例：错误的IP地址格式_2
2019-05-15 16:40:38,931-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第21条测试用例：IP地址为空
2019-05-15 16:40:38,954-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 16:43:09,721-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:------开始执行测试用例-----
2019-05-15 16:43:09,864-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 16:43:10,226-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 16:43:10,282-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：同一个用户名进行注册
2019-05-15 16:43:10,288-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：验证码和手机号不匹配
2019-05-15 16:43:10,295-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：验证码失效
2019-05-15 16:43:10,301-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：验证码为空
2019-05-15 16:43:10,309-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：验证码少于6位
2019-05-15 16:43:10,316-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：验证码多于6位
2019-05-15 16:43:10,320-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：验证码包含其他字符
2019-05-15 16:43:10,326-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：用户名为空
2019-05-15 16:43:10,332-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第11条测试用例：渠道信息非1、2、3
2019-05-15 16:43:10,336-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第12条测试用例：渠道信息非数字
2019-05-15 16:43:10,341-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第13条测试用例：渠道信息为空
2019-05-15 16:43:10,347-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第14条测试用例：密码为空
2019-05-15 16:43:10,351-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第15条测试用例：手机号少于11位
2019-05-15 16:43:10,362-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第16条测试用例：手机号多余11位
2019-05-15 16:43:10,367-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第17条测试用例：手机号包含非数字
2019-05-15 16:43:10,378-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第18条测试用例：手机号为空
2019-05-15 16:43:10,383-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第19条测试用例：错误的IP地址格式_1
2019-05-15 16:43:10,390-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第20条测试用例：错误的IP地址格式_2
2019-05-15 16:43:10,396-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第21条测试用例：IP地址为空
2019-05-15 16:43:10,402-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 16:44:05,844-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:------开始执行测试用例-----
2019-05-15 16:44:06,238-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 16:44:06,732-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 16:44:06,742-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：同一个用户名进行注册
2019-05-15 16:44:06,747-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：验证码和手机号不匹配
2019-05-15 16:44:06,754-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：验证码失效
2019-05-15 16:44:06,758-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：验证码为空
2019-05-15 16:44:06,773-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：验证码少于6位
2019-05-15 16:44:06,780-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：验证码多于6位
2019-05-15 16:44:06,785-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：验证码包含其他字符
2019-05-15 16:44:06,793-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：用户名为空
2019-05-15 16:44:06,806-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第11条测试用例：渠道信息非1、2、3
2019-05-15 16:44:06,811-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第12条测试用例：渠道信息非数字
2019-05-15 16:44:06,818-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第13条测试用例：渠道信息为空
2019-05-15 16:44:06,827-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第14条测试用例：密码为空
2019-05-15 16:44:06,834-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第15条测试用例：手机号少于11位
2019-05-15 16:44:06,840-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第16条测试用例：手机号多余11位
2019-05-15 16:44:06,847-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第17条测试用例：手机号包含非数字
2019-05-15 16:44:06,853-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第18条测试用例：手机号为空
2019-05-15 16:44:06,862-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第19条测试用例：错误的IP地址格式_1
2019-05-15 16:44:06,872-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第20条测试用例：错误的IP地址格式_2
2019-05-15 16:44:06,882-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第21条测试用例：IP地址为空
2019-05-15 16:44:06,893-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 16:47:40,874-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:------开始执行测试用例-----
2019-05-15 16:47:41,015-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 16:47:41,816-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 16:47:41,825-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：同一个用户名进行注册
2019-05-15 16:47:41,829-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：验证码和手机号不匹配
2019-05-15 16:47:41,836-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：验证码失效
2019-05-15 16:47:41,843-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：验证码为空
2019-05-15 16:47:41,851-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：验证码少于6位
2019-05-15 16:47:41,862-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：验证码多于6位
2019-05-15 16:47:41,869-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：验证码包含其他字符
2019-05-15 16:47:41,873-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：用户名为空
2019-05-15 16:47:41,879-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第11条测试用例：渠道信息非1、2、3
2019-05-15 16:47:41,888-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第12条测试用例：渠道信息非数字
2019-05-15 16:47:41,899-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第13条测试用例：渠道信息为空
2019-05-15 16:47:41,908-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第14条测试用例：密码为空
2019-05-15 16:47:41,913-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第15条测试用例：手机号少于11位
2019-05-15 16:47:41,922-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第16条测试用例：手机号多余11位
2019-05-15 16:47:41,933-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第17条测试用例：手机号包含非数字
2019-05-15 16:47:41,956-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第18条测试用例：手机号为空
2019-05-15 16:47:41,960-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第19条测试用例：错误的IP地址格式_1
2019-05-15 16:47:41,971-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第20条测试用例：错误的IP地址格式_2
2019-05-15 16:47:41,990-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第21条测试用例：IP地址为空
2019-05-15 16:47:42,001-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 16:50:15,982-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:------开始执行测试用例-----
2019-05-15 16:50:16,327-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 16:50:16,957-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 16:50:16,981-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：同一个用户名进行注册
2019-05-15 16:50:16,991-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：验证码和手机号不匹配
2019-05-15 16:50:16,996-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：验证码失效
2019-05-15 16:50:17,006-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：验证码为空
2019-05-15 16:50:17,017-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：验证码少于6位
2019-05-15 16:50:17,023-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：验证码多于6位
2019-05-15 16:50:17,029-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：验证码包含其他字符
2019-05-15 16:50:17,035-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：用户名为空
2019-05-15 16:50:17,041-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第11条测试用例：渠道信息非1、2、3
2019-05-15 16:50:17,052-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第12条测试用例：渠道信息非数字
2019-05-15 16:50:17,066-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第13条测试用例：渠道信息为空
2019-05-15 16:50:17,079-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第14条测试用例：密码为空
2019-05-15 16:50:17,085-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第15条测试用例：手机号少于11位
2019-05-15 16:50:17,100-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第16条测试用例：手机号多余11位
2019-05-15 16:50:17,113-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第17条测试用例：手机号包含非数字
2019-05-15 16:50:17,117-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第18条测试用例：手机号为空
2019-05-15 16:50:17,128-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第19条测试用例：错误的IP地址格式_1
2019-05-15 16:50:17,132-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第20条测试用例：错误的IP地址格式_2
2019-05-15 16:50:17,136-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第21条测试用例：IP地址为空
2019-05-15 16:50:17,149-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 16:53:33,160-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:------开始执行测试用例-----
2019-05-15 16:53:33,321-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 16:53:34,067-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 16:53:34,073-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：同一个用户名进行注册
2019-05-15 16:53:34,080-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：验证码和手机号不匹配
2019-05-15 16:53:34,091-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：验证码失效
2019-05-15 16:53:34,099-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：验证码为空
2019-05-15 16:53:34,107-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：验证码少于6位
2019-05-15 16:53:34,114-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：验证码多于6位
2019-05-15 16:53:34,129-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：验证码包含其他字符
2019-05-15 16:53:34,136-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：用户名为空
2019-05-15 16:53:34,143-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第11条测试用例：渠道信息非1、2、3
2019-05-15 16:53:34,148-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第12条测试用例：渠道信息非数字
2019-05-15 16:53:34,163-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第13条测试用例：渠道信息为空
2019-05-15 16:53:34,169-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第14条测试用例：密码为空
2019-05-15 16:53:34,175-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第15条测试用例：手机号少于11位
2019-05-15 16:53:34,180-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第16条测试用例：手机号多余11位
2019-05-15 16:53:34,186-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第17条测试用例：手机号包含非数字
2019-05-15 16:53:34,193-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第18条测试用例：手机号为空
2019-05-15 16:53:34,197-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第19条测试用例：错误的IP地址格式_1
2019-05-15 16:53:34,207-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第20条测试用例：错误的IP地址格式_2
2019-05-15 16:53:34,215-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第21条测试用例：IP地址为空
2019-05-15 16:53:34,222-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 16:55:00,937-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:------开始执行测试用例-----
2019-05-15 16:55:01,091-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 16:55:01,841-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 16:55:01,851-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：同一个用户名进行注册
2019-05-15 16:55:01,856-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：验证码和手机号不匹配
2019-05-15 16:55:01,876-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：验证码失效
2019-05-15 16:55:01,880-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：验证码为空
2019-05-15 16:55:01,885-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：验证码少于6位
2019-05-15 16:55:01,892-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：验证码多于6位
2019-05-15 16:55:01,897-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：验证码包含其他字符
2019-05-15 16:55:01,908-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：用户名为空
2019-05-15 16:55:01,916-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第11条测试用例：渠道信息非1、2、3
2019-05-15 16:55:01,923-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第12条测试用例：渠道信息非数字
2019-05-15 16:55:01,927-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第13条测试用例：渠道信息为空
2019-05-15 16:55:01,931-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第14条测试用例：密码为空
2019-05-15 16:55:01,941-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第15条测试用例：手机号少于11位
2019-05-15 16:55:01,957-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第16条测试用例：手机号多余11位
2019-05-15 16:55:01,962-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第17条测试用例：手机号包含非数字
2019-05-15 16:55:01,975-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第18条测试用例：手机号为空
2019-05-15 16:55:01,988-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第19条测试用例：错误的IP地址格式_1
2019-05-15 16:55:01,992-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第20条测试用例：错误的IP地址格式_2
2019-05-15 16:55:02,000-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第21条测试用例：IP地址为空
2019-05-15 16:55:02,006-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 16:55:49,135-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:------开始执行测试用例-----
2019-05-15 16:55:49,567-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 16:55:50,206-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 16:55:50,865-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：同一个用户名进行注册
2019-05-15 16:55:51,229-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：验证码和手机号不匹配
2019-05-15 16:55:51,665-test_userRegister-[ERROR]-[my_log.py:39]-[日志信息]:断言出错： :: 短信验证码已丢失 != 手机号错误
2019-05-15 16:55:51,669-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：验证码失效
2019-05-15 16:55:52,834-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：验证码为空
2019-05-15 16:55:53,256-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：验证码少于6位
2019-05-15 16:55:53,611-test_userRegister-[ERROR]-[my_log.py:39]-[日志信息]:断言出错： :: 短信验证码已丢失 != 该手机号已被注册
2019-05-15 16:55:53,619-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：验证码多于6位
2019-05-15 16:55:53,920-test_userRegister-[ERROR]-[my_log.py:39]-[日志信息]:断言出错： :: 短信验证码已丢失 != 该手机号已被注册
2019-05-15 16:55:53,925-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：验证码包含其他字符
2019-05-15 16:55:54,274-test_userRegister-[ERROR]-[my_log.py:39]-[日志信息]:断言出错： :: 短信验证码已丢失 != 该手机号已被注册
2019-05-15 16:55:54,280-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：用户名为空
2019-05-15 16:55:54,547-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第11条测试用例：渠道信息非1、2、3
2019-05-15 16:55:55,474-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第12条测试用例：渠道信息非数字
2019-05-15 16:55:55,804-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第13条测试用例：渠道信息为空
2019-05-15 16:55:56,138-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第14条测试用例：密码为空
2019-05-15 16:55:56,431-test_userRegister-[ERROR]-[my_log.py:39]-[日志信息]:断言出错： :: 密码错误 != 用户UID错误
2019-05-15 16:55:56,434-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第15条测试用例：手机号少于11位
2019-05-15 16:55:56,751-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第16条测试用例：手机号多余11位
2019-05-15 16:55:57,037-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第17条测试用例：手机号包含非数字
2019-05-15 16:55:57,316-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第18条测试用例：手机号为空
2019-05-15 16:55:57,581-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第19条测试用例：错误的IP地址格式_1
2019-05-15 16:55:58,783-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第20条测试用例：错误的IP地址格式_2
2019-05-15 16:55:59,097-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第21条测试用例：IP地址为空
2019-05-15 16:55:59,383-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 17:00:01,477-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:------开始执行测试用例-----
2019-05-15 17:00:01,893-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 17:00:02,754-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 17:00:03,479-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：同一个用户名进行注册
2019-05-15 17:00:03,756-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：验证码和手机号不匹配
2019-05-15 17:00:05,951-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：验证码失效
2019-05-15 17:00:06,350-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：验证码为空
2019-05-15 17:00:06,774-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：验证码少于6位
2019-05-15 17:00:07,244-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：验证码多于6位
2019-05-15 17:00:08,342-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：验证码包含其他字符
2019-05-15 17:00:08,848-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：用户名为空
2019-05-15 17:00:09,333-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第11条测试用例：渠道信息非1、2、3
2019-05-15 17:00:09,961-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第12条测试用例：渠道信息非数字
2019-05-15 17:00:10,411-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第13条测试用例：渠道信息为空
2019-05-15 17:00:11,803-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第14条测试用例：密码为空
2019-05-15 17:00:12,574-test_userRegister-[ERROR]-[my_log.py:39]-[日志信息]:断言出错： :: 密码错误 != 用户UID错误
2019-05-15 17:00:12,594-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第15条测试用例：手机号少于11位
2019-05-15 17:00:13,117-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第16条测试用例：手机号多余11位
2019-05-15 17:00:13,532-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第17条测试用例：手机号包含非数字
2019-05-15 17:00:14,599-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第18条测试用例：手机号为空
2019-05-15 17:00:15,204-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第19条测试用例：错误的IP地址格式_1
2019-05-15 17:00:15,731-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第20条测试用例：错误的IP地址格式_2
2019-05-15 17:00:16,211-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第21条测试用例：IP地址为空
2019-05-15 17:00:17,206-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 17:01:22,707-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:------开始执行测试用例-----
2019-05-15 17:01:23,029-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 17:01:23,484-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 17:01:23,566-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：同一个用户名进行注册
2019-05-15 17:01:23,573-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：验证码和手机号不匹配
2019-05-15 17:01:23,594-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：验证码失效
2019-05-15 17:01:23,598-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：验证码为空
2019-05-15 17:01:24,164-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：验证码少于6位
2019-05-15 17:01:24,628-test_userRegister-[ERROR]-[my_log.py:39]-[日志信息]:断言出错： :: 短信验证码已丢失 != 验证码错误
2019-05-15 17:01:24,635-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：验证码多于6位
2019-05-15 17:01:24,975-test_userRegister-[ERROR]-[my_log.py:39]-[日志信息]:断言出错： :: 短信验证码已丢失 != 验证码错误
2019-05-15 17:01:24,996-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：验证码包含其他字符
2019-05-15 17:01:25,337-test_userRegister-[ERROR]-[my_log.py:39]-[日志信息]:断言出错： :: 短信验证码已丢失 != 验证码错误
2019-05-15 17:01:25,347-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：用户名为空
2019-05-15 17:01:25,353-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第11条测试用例：渠道信息非1、2、3
2019-05-15 17:01:25,361-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第12条测试用例：渠道信息非数字
2019-05-15 17:01:25,366-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第13条测试用例：渠道信息为空
2019-05-15 17:01:25,375-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第14条测试用例：密码为空
2019-05-15 17:01:25,383-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第15条测试用例：手机号少于11位
2019-05-15 17:01:25,394-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第16条测试用例：手机号多余11位
2019-05-15 17:01:25,399-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第17条测试用例：手机号包含非数字
2019-05-15 17:01:25,404-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第18条测试用例：手机号为空
2019-05-15 17:01:25,411-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第19条测试用例：错误的IP地址格式_1
2019-05-15 17:01:25,419-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第20条测试用例：错误的IP地址格式_2
2019-05-15 17:01:25,425-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第21条测试用例：IP地址为空
2019-05-15 17:01:25,429-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 17:07:09,908-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:------开始执行测试用例-----
2019-05-15 17:07:10,046-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 17:07:10,647-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 17:07:11,344-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：同一个用户名进行注册
2019-05-15 17:07:11,699-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：验证码和手机号不匹配
2019-05-15 17:07:12,207-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：验证码失效
2019-05-15 17:07:12,827-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：验证码为空
2019-05-15 17:07:13,098-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：验证码少于6位
2019-05-15 17:07:13,472-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：验证码多于6位
2019-05-15 17:07:13,808-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：验证码包含其他字符
2019-05-15 17:07:14,153-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：用户名为空
2019-05-15 17:07:14,631-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第11条测试用例：渠道信息非1、2、3
2019-05-15 17:07:14,931-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第12条测试用例：渠道信息非数字
2019-05-15 17:07:15,218-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第13条测试用例：渠道信息为空
2019-05-15 17:07:15,818-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第14条测试用例：密码为空
2019-05-15 17:07:16,145-test_userRegister-[ERROR]-[my_log.py:39]-[日志信息]:断言出错： :: 密码错误 != 用户UID错误
2019-05-15 17:07:16,153-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第15条测试用例：手机号少于11位
2019-05-15 17:07:16,486-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第16条测试用例：手机号多余11位
2019-05-15 17:07:16,774-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第17条测试用例：手机号包含非数字
2019-05-15 17:07:17,081-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第18条测试用例：手机号为空
2019-05-15 17:07:17,384-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第19条测试用例：错误的IP地址格式_1
2019-05-15 17:07:17,669-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第20条测试用例：错误的IP地址格式_2
2019-05-15 17:07:17,940-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第21条测试用例：IP地址为空
2019-05-15 17:07:18,222-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 19:01:09,802-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 19:01:09,952-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 19:01:10,406-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 19:01:10,639-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 19:01:11,221-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 19:01:11,500-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 19:01:11,507-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：实名认证过的账号再次认证
2019-05-15 19:01:11,510-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：用户id为空
2019-05-15 19:01:11,621-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：Unmarshalling Error: For input string: "" 
2019-05-15 19:01:11,890-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：真实姓名为空
2019-05-15 19:01:11,898-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：身份证号为空
2019-05-15 19:01:11,908-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：身份证号不合法
2019-05-15 19:01:11,913-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：用户id为假
2019-05-15 19:01:12,038-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：用户不存在
2019-05-15 19:01:12,328-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：真实姓名不合法
2019-05-15 19:01:12,333-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 19:04:49,285-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 19:04:49,409-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 19:04:49,770-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 19:04:50,023-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 19:04:50,517-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 19:04:50,752-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 19:04:50,758-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：实名认证过的账号再次认证
2019-05-15 19:04:50,770-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：用户id为空
2019-05-15 19:04:50,988-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：Unmarshalling Error: For input string: "" 
2019-05-15 19:04:51,210-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：真实姓名为空
2019-05-15 19:04:51,221-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：身份证号为空
2019-05-15 19:04:51,224-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：身份证号不合法
2019-05-15 19:04:51,228-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：用户id为假
2019-05-15 19:04:51,422-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：用户不存在
2019-05-15 19:04:51,640-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：真实姓名不合法
2019-05-15 19:04:51,642-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 19:06:37,254-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 19:06:37,387-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 19:06:37,797-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 19:06:38,148-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 19:06:38,736-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 19:06:38,954-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 19:06:38,971-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：实名认证过的账号再次认证
2019-05-15 19:06:38,976-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：用户id为空
2019-05-15 19:06:39,271-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：Unmarshalling Error: For input string: "" 
2019-05-15 19:06:39,436-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：真实姓名为空
2019-05-15 19:06:39,439-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：身份证号为空
2019-05-15 19:06:39,442-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：身份证号不合法
2019-05-15 19:06:39,445-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：用户id为假
2019-05-15 19:06:40,253-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：用户不存在
2019-05-15 19:06:40,444-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：真实姓名不合法
2019-05-15 19:06:40,447-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 19:09:32,421-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 19:09:32,581-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 19:09:33,581-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 19:09:33,823-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 19:09:34,663-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 19:09:34,882-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 19:09:34,898-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：实名认证过的账号再次认证
2019-05-15 19:09:34,901-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：用户id为空
2019-05-15 19:09:35,014-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：Unmarshalling Error: For input string: "" 
2019-05-15 19:09:35,232-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：真实姓名为空
2019-05-15 19:09:35,239-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：身份证号为空
2019-05-15 19:09:35,243-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：身份证号不合法
2019-05-15 19:09:35,252-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：用户id为假
2019-05-15 19:09:35,540-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：用户不存在
2019-05-15 19:09:35,739-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：真实姓名不合法
2019-05-15 19:09:35,742-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 19:10:50,364-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 19:10:50,507-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 19:10:50,861-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 19:10:51,132-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 19:10:51,649-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 19:10:51,907-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 19:10:51,913-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：实名认证过的账号再次认证
2019-05-15 19:10:51,923-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：用户id为空
2019-05-15 19:10:52,291-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：Unmarshalling Error: For input string: "" 
2019-05-15 19:10:52,469-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：真实姓名为空
2019-05-15 19:10:52,473-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：身份证号为空
2019-05-15 19:10:52,477-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：身份证号不合法
2019-05-15 19:10:52,483-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：用户id为假
2019-05-15 19:10:52,638-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：用户不存在
2019-05-15 19:10:52,813-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：真实姓名不合法
2019-05-15 19:10:52,821-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 19:11:37,896-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 19:11:38,032-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 19:11:38,382-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 19:11:38,623-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 19:11:39,130-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 19:11:39,364-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 19:11:39,619-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 19:11:39,855-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：实名认证过的账号再次认证
2019-05-15 19:11:40,207-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：该身份证已经进行过实名认证
2019-05-15 19:11:40,397-test_verifiedUserAuth-[ERROR]-[my_log.py:39]-[日志信息]:断言出错： :: None != 该身份证已经进行过实名认证
2019-05-15 19:11:40,405-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：用户id为空
2019-05-15 19:11:40,503-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：Unmarshalling Error: For input string: "" 
2019-05-15 19:11:40,677-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：真实姓名为空
2019-05-15 19:11:40,840-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：真实姓名错误
2019-05-15 19:11:41,110-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：身份证号为空
2019-05-15 19:11:41,228-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：身份证号错误
2019-05-15 19:11:41,406-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：身份证号不合法
2019-05-15 19:11:41,524-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：身份证号检验错误
2019-05-15 19:11:41,726-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：用户id为假
2019-05-15 19:11:41,861-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：用户不存在
2019-05-15 19:11:42,031-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：真实姓名不合法
2019-05-15 19:11:42,175-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：真实姓名必须为中文
2019-05-15 19:11:42,343-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 19:12:22,247-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 19:12:22,690-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 19:12:23,160-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 19:12:23,382-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 19:12:23,881-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 19:12:24,230-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 19:12:24,410-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 19:12:24,679-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：实名认证过的账号再次认证
2019-05-15 19:12:24,835-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：该身份证已经进行过实名认证
2019-05-15 19:12:25,043-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：用户id为空
2019-05-15 19:12:25,224-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：Unmarshalling Error: For input string: "" 
2019-05-15 19:12:25,406-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：真实姓名为空
2019-05-15 19:12:25,631-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：真实姓名错误
2019-05-15 19:12:25,800-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：身份证号为空
2019-05-15 19:12:25,914-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：身份证号错误
2019-05-15 19:12:26,103-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：身份证号不合法
2019-05-15 19:12:26,292-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：身份证号检验错误
2019-05-15 19:12:26,484-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：用户id为假
2019-05-15 19:12:26,607-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：用户不存在
2019-05-15 19:12:26,787-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：真实姓名不合法
2019-05-15 19:12:26,913-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：真实姓名必须为中文
2019-05-15 19:12:27,163-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 22:01:41,760-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 22:01:42,197-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 22:01:42,602-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 22:01:42,905-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 22:01:43,463-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 22:01:43,707-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 22:01:43,947-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 22:01:44,257-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：实名认证过的账号再次认证
2019-05-15 22:01:44,426-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：该身份证已经进行过实名认证
2019-05-15 22:01:44,615-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：用户id为空
2019-05-15 22:01:44,721-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：Unmarshalling Error: For input string: "" 
2019-05-15 22:01:44,905-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：真实姓名为空
2019-05-15 22:01:45,031-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：真实姓名错误
2019-05-15 22:01:45,207-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：身份证号为空
2019-05-15 22:01:45,347-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：身份证号错误
2019-05-15 22:01:45,539-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：身份证号不合法
2019-05-15 22:01:45,690-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：身份证号检验错误
2019-05-15 22:01:45,870-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：用户id为假
2019-05-15 22:01:45,998-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：用户不存在
2019-05-15 22:01:46,186-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：真实姓名不合法
2019-05-15 22:01:46,319-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：真实姓名必须为中文
2019-05-15 22:01:46,517-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 22:03:38,170-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 22:03:38,293-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 22:03:38,707-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 22:03:38,916-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 22:03:39,400-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 22:03:39,658-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 22:03:39,816-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 22:03:40,145-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：实名认证过的账号再次认证
2019-05-15 22:03:40,284-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：该身份证已经进行过实名认证
2019-05-15 22:03:40,470-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：用户id为空
2019-05-15 22:03:40,601-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：Unmarshalling Error: For input string: "" 
2019-05-15 22:03:40,766-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：真实姓名为空
2019-05-15 22:03:40,891-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：真实姓名错误
2019-05-15 22:03:41,054-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：身份证号为空
2019-05-15 22:03:41,171-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：身份证号错误
2019-05-15 22:03:41,354-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：身份证号不合法
2019-05-15 22:03:41,461-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：身份证号检验错误
2019-05-15 22:03:41,723-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：用户id为假
2019-05-15 22:03:41,849-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：用户不存在
2019-05-15 22:03:42,101-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：真实姓名不合法
2019-05-15 22:03:42,235-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：真实姓名必须为中文
2019-05-15 22:03:42,403-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 22:09:52,393-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 22:09:52,543-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 22:09:52,932-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 22:09:53,152-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 22:09:53,662-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 22:09:53,868-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 22:09:54,110-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 22:09:54,332-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：实名认证过的账号再次认证
2019-05-15 22:09:54,492-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：该身份证已经进行过实名认证
2019-05-15 22:09:54,708-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：用户id为空
2019-05-15 22:09:54,818-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：Unmarshalling Error: For input string: "" 
2019-05-15 22:09:55,007-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：真实姓名为空
2019-05-15 22:09:55,153-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：真实姓名错误
2019-05-15 22:09:55,331-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：身份证号为空
2019-05-15 22:09:55,460-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：身份证号错误
2019-05-15 22:09:55,628-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：身份证号不合法
2019-05-15 22:09:55,764-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：身份证号检验错误
2019-05-15 22:09:55,961-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：用户id为假
2019-05-15 22:09:56,100-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：用户不存在
2019-05-15 22:09:56,274-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：真实姓名不合法
2019-05-15 22:09:56,390-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：真实姓名必须为中文
2019-05-15 22:09:56,582-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 22:17:41,656-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 22:17:41,783-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 22:17:42,156-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 22:17:42,386-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 22:17:42,978-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 22:17:43,196-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 22:17:43,388-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 22:17:43,632-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：实名认证过的账号再次认证
2019-05-15 22:17:43,779-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：该身份证已经进行过实名认证
2019-05-15 22:17:44,022-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：用户id为空
2019-05-15 22:17:44,209-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：Unmarshalling Error: For input string: "" 
2019-05-15 22:17:44,414-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：真实姓名为空
2019-05-15 22:17:44,592-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：真实姓名错误
2019-05-15 22:17:44,780-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：身份证号为空
2019-05-15 22:17:44,923-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：身份证号错误
2019-05-15 22:17:45,205-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：身份证号不合法
2019-05-15 22:17:45,330-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：身份证号检验错误
2019-05-15 22:17:45,609-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：用户id为假
2019-05-15 22:17:45,733-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：用户不存在
2019-05-15 22:17:45,950-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：真实姓名不合法
2019-05-15 22:17:46,090-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：真实姓名必须为中文
2019-05-15 22:17:46,297-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 22:34:38,677-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 22:34:38,804-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 22:34:39,181-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:34:39,216-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 22:34:39,238-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 22:34:39,241-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：正常绑定银行卡
2019-05-15 22:34:39,244-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 22:35:06,072-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 22:35:06,205-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 22:35:06,568-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:35:06,799-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 22:35:07,324-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:35:07,325-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:执行的sql语句是：SELECT Fuid FROM user_db.t_user_info WHERE Fuser_id ='abai'
2019-05-15 22:35:07,384-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的id是：100010893
2019-05-15 22:35:07,560-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 22:35:07,566-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：正常绑定银行卡
2019-05-15 22:35:07,573-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 22:36:30,573-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 22:36:30,703-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 22:36:31,084-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:36:31,320-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 22:36:31,834-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:36:31,836-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:执行的sql语句是：SELECT Fuid FROM user_db.t_user_info WHERE Fuser_id ='duyang'
2019-05-15 22:36:31,894-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的id是：100010896
2019-05-15 22:36:32,058-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 22:36:32,066-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：正常绑定银行卡
2019-05-15 22:36:32,070-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 22:37:34,078-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 22:37:34,207-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 22:37:34,586-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:37:34,835-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 22:37:35,312-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:37:35,314-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:执行的sql语句是：SELECT Fuid FROM user_db.t_user_info WHERE Fuser_id ='txia'
2019-05-15 22:37:35,375-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的id是：100010898
2019-05-15 22:37:35,564-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 22:37:35,570-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：正常绑定银行卡
2019-05-15 22:37:35,577-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 22:40:11,471-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 22:40:11,611-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 22:40:12,024-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:40:12,263-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 22:40:12,766-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:40:12,767-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:执行的sql语句是：SELECT Fuid FROM user_db.t_user_info WHERE Fuser_id ='kongjie'
2019-05-15 22:40:12,828-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的id是：100010900
2019-05-15 22:40:13,013-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 22:40:13,205-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:40:13,462-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：正常绑定银行卡
2019-05-15 22:40:13,521-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 22:43:57,381-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 22:43:57,521-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 22:43:57,892-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:43:58,079-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 22:43:58,564-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:43:58,567-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:执行的sql语句是：SELECT Fuid FROM user_db.t_user_info WHERE Fuser_id ='gongjun'
2019-05-15 22:43:58,625-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的id是：100010905
2019-05-15 22:43:58,692-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 22:43:58,877-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:43:59,002-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：正常绑定银行卡
2019-05-15 22:43:59,141-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：银行卡号检验错误
2019-05-15 22:43:59,221-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 22:44:12,870-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 22:44:12,998-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 22:44:13,367-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:44:13,597-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 22:44:14,083-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:44:14,085-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:执行的sql语句是：SELECT Fuid FROM user_db.t_user_info WHERE Fuser_id ='yangfeng'
2019-05-15 22:44:14,143-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的id是：100010906
2019-05-15 22:44:14,324-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 22:44:14,502-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:44:14,788-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：正常绑定银行卡
2019-05-15 22:44:14,919-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：银行卡号检验错误
2019-05-15 22:44:15,128-test_bindBankCard-[ERROR]-[my_log.py:39]-[日志信息]:断言出错： :: ok != 银行卡号检验错误
2019-05-15 22:44:15,133-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 22:45:16,693-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 22:45:16,829-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 22:45:17,172-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:45:17,407-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 22:45:17,884-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:45:17,886-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:执行的sql语句是：SELECT Fuid FROM user_db.t_user_info WHERE Fuser_id ='qiang54'
2019-05-15 22:45:17,946-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的id是：100010908
2019-05-15 22:45:18,158-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 22:45:18,347-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:45:18,618-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：正常绑定银行卡
2019-05-15 22:45:18,622-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:生成的银行卡号是：6217006454470697474
2019-05-15 22:45:18,740-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：银行卡号检验错误
2019-05-15 22:45:18,924-test_bindBankCard-[ERROR]-[my_log.py:39]-[日志信息]:断言出错： :: ok != 银行卡号检验错误
2019-05-15 22:45:18,929-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 22:45:45,393-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 22:45:45,535-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 22:45:45,915-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:45:46,161-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 22:45:46,649-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:45:46,650-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:执行的sql语句是：SELECT Fuid FROM user_db.t_user_info WHERE Fuser_id ='xiuying49'
2019-05-15 22:45:46,707-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的id是：100010909
2019-05-15 22:45:46,903-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 22:45:47,067-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:45:47,332-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：正常绑定银行卡
2019-05-15 22:45:47,476-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：银行卡号检验错误
2019-05-15 22:45:47,701-test_bindBankCard-[ERROR]-[my_log.py:39]-[日志信息]:断言出错： :: ok != 银行卡号检验错误
2019-05-15 22:45:47,711-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 22:49:29,237-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 22:49:29,386-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 22:49:29,839-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:49:30,067-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 22:49:30,541-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:49:30,543-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:执行的sql语句是：SELECT Fuid FROM user_db.t_user_info WHERE Fuser_id ='vzhao'
2019-05-15 22:49:30,610-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的id是：100010910
2019-05-15 22:49:30,815-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 22:49:30,992-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:49:31,239-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：正常绑定银行卡
2019-05-15 22:49:31,388-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：用户交易密码不正确或未配置
2019-05-15 22:49:31,589-test_bindBankCard-[ERROR]-[my_log.py:39]-[日志信息]:断言出错： :: ok != 用户交易密码不正确或未配置
2019-05-15 22:49:31,600-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 22:59:24,725-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 22:59:24,909-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 22:59:25,328-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:59:25,619-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 22:59:26,087-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:59:26,088-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:执行的sql语句是：SELECT Fuid FROM user_db.t_user_info WHERE Fuser_id ='mengqiang'
2019-05-15 22:59:26,179-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的id是：100010911
2019-05-15 22:59:26,394-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 22:59:26,564-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：ok
2019-05-15 22:59:26,913-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：正常绑定银行卡
2019-05-15 22:59:27,062-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:得到的响应结果是：银行卡号检验错误
2019-05-15 22:59:27,317-test_bindBankCard-[ERROR]-[my_log.py:39]-[日志信息]:断言出错：'ok' != '银行卡号检验错误'
- ok
+ 银行卡号检验错误

2019-05-15 22:59:27,319-test_bindBankCard-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 22:59:27,321-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 22:59:27,440-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常操作
2019-05-15 22:59:27,865-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：ip为空
2019-05-15 22:59:28,151-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：短信模板为空
2019-05-15 22:59:28,505-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：手机号为空
2019-05-15 22:59:28,834-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：短信模板非1
2019-05-15 22:59:29,268-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：错误的手机号码
2019-05-15 22:59:29,617-F:\work\webservice_practice\testcase\test_sendMCode.py-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 22:59:29,620-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:------开始执行测试用例-----
2019-05-15 22:59:29,750-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 22:59:30,190-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 22:59:30,630-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：同一个用户名进行注册
2019-05-15 22:59:30,964-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：验证码和手机号不匹配
2019-05-15 22:59:31,405-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：验证码失效
2019-05-15 22:59:31,725-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：验证码为空
2019-05-15 22:59:32,020-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：验证码少于6位
2019-05-15 22:59:32,381-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：验证码多于6位
2019-05-15 22:59:32,704-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：验证码包含其他字符
2019-05-15 22:59:33,031-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：用户名为空
2019-05-15 22:59:33,336-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第11条测试用例：渠道信息非1、2、3
2019-05-15 22:59:33,633-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第12条测试用例：渠道信息非数字
2019-05-15 22:59:33,908-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第13条测试用例：渠道信息为空
2019-05-15 22:59:34,234-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第14条测试用例：密码为空
2019-05-15 22:59:34,570-test_userRegister-[ERROR]-[my_log.py:39]-[日志信息]:断言出错：'密码错误' != '用户UID错误'
- 密码错误
+ 用户UID错误

2019-05-15 22:59:34,572-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第15条测试用例：手机号少于11位
2019-05-15 22:59:34,886-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第16条测试用例：手机号多余11位
2019-05-15 22:59:35,163-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第17条测试用例：手机号包含非数字
2019-05-15 22:59:35,470-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第18条测试用例：手机号为空
2019-05-15 22:59:35,769-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第19条测试用例：错误的IP地址格式_1
2019-05-15 22:59:36,105-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第20条测试用例：错误的IP地址格式_2
2019-05-15 22:59:36,377-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:开始执行第21条测试用例：IP地址为空
2019-05-15 22:59:36,671-test_userRegister-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
2019-05-15 22:59:36,672-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----开始执行测试用例-----
2019-05-15 22:59:36,783-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第1条测试用例：正常发送验证码
2019-05-15 22:59:36,989-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 22:59:37,216-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第2条测试用例：正常注册
2019-05-15 22:59:37,462-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 22:59:37,674-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第3条测试用例：正常实名认证
2019-05-15 22:59:37,861-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：ok
2019-05-15 22:59:38,102-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第4条测试用例：实名认证过的账号再次认证
2019-05-15 22:59:38,238-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：该身份证已经进行过实名认证
2019-05-15 22:59:38,398-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第5条测试用例：用户id为空
2019-05-15 22:59:38,552-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：Unmarshalling Error: For input string: "" 
2019-05-15 22:59:38,705-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第6条测试用例：真实姓名为空
2019-05-15 22:59:38,849-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：真实姓名错误
2019-05-15 22:59:39,019-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第7条测试用例：身份证号为空
2019-05-15 22:59:39,128-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：身份证号错误
2019-05-15 22:59:39,274-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第8条测试用例：身份证号不合法
2019-05-15 22:59:39,388-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：身份证号检验错误
2019-05-15 22:59:39,562-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第9条测试用例：用户id为假
2019-05-15 22:59:39,713-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：用户不存在
2019-05-15 22:59:39,881-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:开始执行第10条测试用例：真实姓名不合法
2019-05-15 22:59:39,988-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:响应的结果是：真实姓名必须为中文
2019-05-15 22:59:40,144-test_verifiedUserAuth-[INFO]-[my_log.py:35]-[日志信息]:-----测试用例执行完毕-----
